services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_cron
      - -c
      - cron.database_name=${POSTGRES_DB}
      - -c
      - cron.timezone=Asia/Kuala_Lumpur

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    environment:
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000

volumes:
  postgres_data:
