import type { Product } from "../types/product";

export const mockProducts: Product[] = [
  {
    id: "totoro-velour",
    name: "Totoro Velour Edition",
    price: 4500,
    image: "/homepage/plush-toys-on-wooden-shelf.png",
    category: "Plush Toys",
    brand: "Studio Ghibli",
    rating: 4.9,
    label: "New Arrival",
    variant: "new",
  },
  {
    id: "sakura-bunbun",
    name: "Sakura Bun-Bun",
    price: 3200,
    image: "/homepage/blue-maneki-neko-figurine-display-case.png",
    category: "Plush Toys",
    brand: "Harajuku Artisans",
    rating: 5.0,
  },
  {
    id: "anya-star",
    name: "Anya Star Edition",
    price: 12800,
    image: "/homepage/komorebi-gift-atelier-wrapped-boxes.png",
    category: "Anime Figurines",
    brand: "Good Smile Company",
    rating: 4.8,
    label: "Limited",
    variant: "limited",
  },
  {
    id: "tea-ritual-mini",
    name: "Tea Ritual Mini Set",
    price: 5900,
    image: "/homepage/komorebi-stationery-fountain-pen.png",
    category: "Stationery",
    brand: "Kyoto Traditions",
    rating: 4.7,
  },
  {
    id: "soot-sprite-fluff",
    name: "Soot Sprite Fluff",
    price: 1800,
    image: "/homepage/plush-toys-on-wooden-shelf.png",
    category: "Plush Toys",
    brand: "Studio Ghibli",
    rating: 4.9,
  },
  {
    id: "neo-shogun-neko",
    name: "Neo-Shogun Neko",
    price: 22500,
    image: "/homepage/blue-maneki-neko-figurine-display-case.png",
    category: "Vinyl Art",
    brand: "Art Toy Lab",
    rating: 5.0,
    label: "Collector's Choice",
    variant: "collector",
  },
];
